### PR TITLE
Asian parent-checking the website

### LINKED ISSUE #34: I have been ignored.
Solution: I will submit a patch.

### PR DESCRIPTION
**Pull request by cytronicoder**
Fixes #34 nicely.

I also noticed a bunch of site issues that I will submit a PR for in a sec

### CODE REVIEW

**Comment by cytronicoder** [comment]
I did a bit more of editing just for everyone's eyes; it should be easier to add team members now (along with some redundant styling removals)

**Comment by cytronicoder** [comment]
Rename PR to accurately reflect that I did

**Comment by cytronicoder** [comment]
Better description to tackle #36 as well

**Comment by cytronicoder** [comment]
Fixed #36 afaik

**Review by icepcp — APPROVED** [review]
looks good! thank you for your contribution :)

**Pull request merged**
